### ISSUE TITLE
[Feature request] long double conversion routines

### ISSUE THREAD

**Issue by EdSchouten** [google/double-conversion#10]
Right now I'm developing a C library for a system called CloudABI (more details: https://github.com/NuxiNL/cloudlibc). As this double-conversion code is supposed to be faster than David M. Gay's gdtoa implementation (and also a lot more readable), my intent is to use this code to implement strto{f,d,ld}() and printf()'s %f. So far things are going all right. strtof() and strtod() already work as expected. My next task is getting printf() to work.

It looks like double-conversion only supports float and double. This is a bit problematic, as strtold() and printf()'s %Lf are supposed to parse and print floating point numbers with larger precision. Are there any plans to add 80/128-bit long double support to double-conversion?

Thanks!

**Comment by floitsch** [comment]
There are no plans to support long doubles.
I think you could extract the (fallback) bignum implementation of the library to support it, though. You would probably need to reserve more memory for the bignums (since it's currently calculated for 64 bit doubles) and you would also run into the limits of the diy_fp class (which only allows for a 64 bit significand). The algorithm itself should, however, work.
