### ISSUE TITLE
Assertion failure in DivideModuloIntBignum

### ISSUE THREAD

**Issue by effzeh** [google/double-conversion#40]
[This](https://github.com/google/double-conversion/blob/master/double-conversion/bignum.cc#L507) assertion in bignum.cc in `DivideModuloIntBignum` fails for the two bignums `A = 0x11100000` and `B = 100000`. But `A/B = 0x111` and as I understand it the function should be able two handle these inputs. 

Now, I don't understand the intent of this assertion. It seems to check that the leading bigit of `other` is `>= 2^(28-4)` which indicates that `other` should be some kind of normalized...? Just commenting it out, the function produces the correct results... so, is the assertion correct here?

FWIW, there are other numbers for which the assertion fails, which came up while trying to speed up GenerateCountedDigits in bignum-dtoa.cc: https://github.com/effzeh/double-conversion/commit/57a09e673e57abe2fc78a8892da9cc8019d7c92a

**Comment by floitschG** [comment]
It's an efficiency check, and safe to remove for correct computations.

The loop condition guarantees that `this.BigitLength > other.BigitLength`. Say `x` is the first digit of `this` and `y` is the first digit of `other`. If we assume that the result of the division is very close (less than 10), then we know that `(x * (1 << kBigitSize)) / y` should be at most 10 (or very close to that). That's exactly the assertion here.
The first assertion guarantees that `y` is not too small to make the result be greater than `10` (or `16`, the actual value in the assertion), and the second assertion checks that `x` is not too big.
The second assertion could have a much stronger check (not just `0x10000`, but rather `16`). However, we don't really care too much for `x` since we subtract `x * other` anyway. So, as long as `y` has a big value, we will not have many iterations of the loop.

Basically, we wanted to make sure that the naive approach of subtracting multiple times `x * other` is not going to take too long. If you reached this assertion, you might want to consider changing the code to speed up this case.

For example (and I haven't tried this):
``` c++
while (BigitLength() > other.BigitLength()) {
    int shift = 0;
    Chunk otherFirst = other.bigits_[other.used_digits_ - 1];
    while (otherFirst < (1 << kBigitSize)) {
        otherFirst <<= 1; shift++;
    }
    // Remove the multiples of the first digit.
    // Example this = 23 and other equals 9. -> Remove 2 multiples.
    result += static_cast<uint16_t>(bigits_[used_digits_ - 1]) << shift;
    SubtractTimes(other, bigits_[used_digits_ - 1] << shift);
  }
```

I haven't touched this code in a very long time, so I hope this makes sense.

**Comment by effzeh** [comment]
Thanks!!
