### ISSUE TITLE
FixupMultiply10: Why do you add delta_plus to numerator

### ISSUE THREAD

**Issue by amanjiang** [google/double-conversion#62]
The routine from bignum-dtoa.cc:

``` c++
    static void FixupMultiply10(int estimated_power, bool is_even,
                                int* decimal_point,
                                Bignum* numerator, Bignum* denominator,
                                Bignum* delta_minus, Bignum* delta_plus) {
      bool in_range;
      if (is_even) {
        // For IEEE doubles half-way cases (in decimal system numbers ending with 5)
        // are rounded to the closest floating-point number with even significand.
        in_range = Bignum::PlusCompare(*numerator, *delta_plus, *denominator) >= 0;
      } else {
        in_range = Bignum::PlusCompare(*numerator, *delta_plus, *denominator) > 0;
      }
      if (in_range) {
        // Since numerator + delta_plus >= denominator we already have
        // 1 <= numerator/denominator < 10. Simply update the estimated_power.
        *decimal_point = estimated_power + 1;
      } else {
        *decimal_point = estimated_power;
        numerator->Times10();
        if (Bignum::Equal(*delta_minus, *delta_plus)) {
          delta_minus->Times10();
          delta_plus->AssignBignum(*delta_minus);
        } else {
          delta_minus->Times10();
          delta_plus->Times10();
        }
      }
    }
```

Why do you add delta_plus to numerator and then compare the sum to denominator ? Do we really need delta_plus here ? Can we just write (and forget is_even as well):

    in_range = Bignum::Compare(*numerator, *denominator) >= 0;

It works fine for BignumDtoaGayShortest test, too.

According to my understanding the numerator must greater than or equal to denominator here, so that no leading 0 digit will be produced by GenerateShortestDigits.

**Comment by floitsch** [comment]
Sorry this reply took so long...
You are probably right that it's not necessary. I wrote the code in accordance to the PLDI paper which proves that this approach is correct. A few weeks back I tried to prove that the algorithm is still correct without adding delta_plus. It didn't finish (although I admittedly didn't spend much time on it).
Given that the adding shouldn't be expensive I prefer not to change it. (It just has been too long since I wrote it, and I would need significant effort to get completely back into the algorithm).
If there are real downsides to adding it, I could give it a bit more attention, though.

**Comment by amanjiang** [comment]
I was wrong, adding it is necessary.

I'm working on a project, and today I found that testcase "1e-23" (vs debugger represents it as "9.9999999999999996e-24") will fail if I change the algorithm. In this case, the first generated digit is 0, then it reached the boundary (in delta plus room), round up, 1.

I'm sorry for this.
